package main.java.bank.object;

public class Mapping {
	
	public static String User = "mngr154622";
	public static String Password = "1234567_8";
	public static String LogInURL = "http://www.demo.guru99.com/V4/index.php";
	public static String ManagerXpath = "//*[@class='heading3']";
	public static String ManagerWelcome = "Welcome To Manager's Page of Guru99 Bank";
	public static String ExcelFilePath = System.getProperty("user.dir")+"\\src\\main\\java\\bank\\object\\";
	public static String ExcelFile = "Bank_Util.xlsx";
	public static String SheetName = "testdata";
	public static String LogInAlert = "User or Password is not valid";
	public static String ScreenshotFilePath = System.getProperty("user.dir")+"\\src\\main\\java\\bank\\screenshots\\Test_Manager_Page_";
	public static String ChangePasswordLink = "Change Password";
	public static String OldPasswordFalse = "123456";
	public static String NewPassword = "123456_7";
	public static String FalseOldPasswordAlert = "Old Password is incorrect";
	public static String HeaderChangePassword = "Change Password";
	public static String ChangePasswordAlert = "Password is Changed";
	public static String CustomerName="Virendra";
	public static String CustomerGende="male";
	public static String CustomerBirthday="04.11.2013";
	public static String CustomerAddress="Jamnagar";
	public static String CustomerCity = "Jamnagar";
	public static String CustomerState="Gujarat";
	public static String CustomerPin="567321";
	public static String CustomerMobile ="8000439024";
	public static String CustomerEmail ="Virendra_27_09_18_1@gmail.com";
	public static String CustomerPassword ="12345678_9";
	public static String CustomerRegisteredSuccessfull = "Customer Registered Successfully!!!";
	public static String AccountTyp = "Savings";
	public static String IniDeposit ="500";
	public static String AccountAddedSuccess ="Account Generated Successfully!!!";
	public static String CustomerID="15906";
	public static String AccountID ="49456";
	public static String AccountDeleteAlert="Do you really want to delete this Account?";
	public static String ManagerHomePageURL = "http://www.demo.guru99.com/v4/manager/Managerhomepage.php";
	public static String AccountDeleteSuccessAlert = "Account Deleted Sucessfully";
	public static String AccountNotExistAlert = "Account does not exist";
	public static String MiniStatementHeader ="Mini Statement Form";
	public static String BalanceEnquiryHeader = "Balance Enquiry Form";
	public static String CustomizedStatementHeader= "Customized Statement Form";
	public static String DeleteCustomerAlert = "Do you really want to delete this Customer?";
	public static String DeleteCustomerNotAvaiAlert = "Customer could not be deleted!!. First delete all accounts of this customer then delete the customer";
	public static String DeleteCustomerSuccessAlert = "Customer deleted Successfully";
	public static String EditCustomerHeader = "Edit Customer Form";
	public static String CustomerNotExistAlert = "Customer does not exist!!";
	public static String DeleteCustomerHeader = "Delete Customer Form";
	public static String CustomerID_2 = "26260";
	public static String AccID_2 = "49523";
	public static String AccNotExist = "9999999999";
	public static String FundTransferHeader = "Fund transfer";
	public static String FundTransferDesc = "cash";
	public static String FundTransferAmount = "500";
	public static String TransferDetailsDesc = "cashTansfer To";
	public static String AccountNotExistAlertFirstPart = "Account ";
	public static String AccountNotExistAlertLastPart = "does not exist!!!";
	public static String AccNoAuthor = "11111";
	public static String FundTransferSameAccAlert = "Payers account No and Payees account No Must Not be Same!!!";
	public static String FundAmountTransferLow = "15000";
	public static String FundTransferLowAlert = "Transfer Failed. Account Balance low!!";
	public static String DepositPageHeader = "Amount Deposit Form";
	public static String DepositDetailsPageHeader = "Transaction details of Deposit for Account ";
	public static String WithdrawalPageHeader = "Amount Withdrawal Form";
	public static String WithdrawalDetailsHeader = "Transaction details of Withdrawal for Account ";
	public static String WithdrawalLowBalanceAlert = "Transaction Failed. Account Balance Low!!!";
	public static String MiniStatementDetailHeader = "Last Five Transaction Details for Account No: ";
	public static String BalanceDetailsPageHeader = "Balance Details for Account ";
	public static String NumberOfTransactionCustomizedStatement = "30";
	public static String WrongDateSelectionAlert = "FromDate field should be lower than ToDate field!!";
	public static String TransactionDetailsHeaderFirstPart = "Transaction Details for Account No: ";
	public static String TransactionDetailsHeaderMiddlePart = " from Date: ";
	public static String TransactionDetailsHeaderLastPart =" to: ";
	public static String EditAccPageHeader = "Edit Account Form";
	public static String EditAccDetailsPageHeader = "Edit Account Entry Form";
	public static String LogOutAlert = "You Have Succesfully Logged Out!!";
	public static String CustomerHomePageURL = "http://www.demo.guru99.com/V4/customer/Customerhomepage.php";
	public static String User_Customer = "28020";

			
}